import type { GameWord } from "./types";

export const words: GameWord[] = [
  // 简单 — 日常物品、动物、食物
  { word: "苹果", hint: "水果", difficulty: "easy" },
  { word: "香蕉", hint: "水果", difficulty: "easy" },
  { word: "西瓜", hint: "水果", difficulty: "easy" },
  { word: "草莓", hint: "水果", difficulty: "easy" },
  { word: "橘子", hint: "水果", difficulty: "easy" },
  { word: "葡萄", hint: "水果", difficulty: "easy" },
  { word: "桃子", hint: "水果", difficulty: "easy" },
  { word: "梨", hint: "水果", difficulty: "easy" },
  { word: "猫", hint: "动物", difficulty: "easy" },
  { word: "狗", hint: "动物", difficulty: "easy" },
  { word: "兔子", hint: "动物", difficulty: "easy" },
  { word: "熊猫", hint: "动物", difficulty: "easy" },
  { word: "大象", hint: "动物", difficulty: "easy" },
  { word: "老虎", hint: "动物", difficulty: "easy" },
  { word: "狮子", hint: "动物", difficulty: "easy" },
  { word: "猴子", hint: "动物", difficulty: "easy" },
  { word: "长颈鹿", hint: "动物", difficulty: "easy" },
  { word: "企鹅", hint: "动物", difficulty: "easy" },
  { word: "蝴蝶", hint: "动物", difficulty: "easy" },
  { word: "鱼", hint: "动物", difficulty: "easy" },
  { word: "鸟", hint: "动物", difficulty: "easy" },
  { word: "太阳", hint: "自然", difficulty: "easy" },
  { word: "月亮", hint: "自然", difficulty: "easy" },
  { word: "星星", hint: "自然", difficulty: "easy" },
  { word: "云", hint: "自然", difficulty: "easy" },
  { word: "雨", hint: "自然", difficulty: "easy" },
  { word: "彩虹", hint: "自然", difficulty: "easy" },
  { word: "山", hint: "自然", difficulty: "easy" },
  { word: "河流", hint: "自然", difficulty: "easy" },
  { word: "花", hint: "植物", difficulty: "easy" },
  { word: "树", hint: "植物", difficulty: "easy" },
  { word: "草", hint: "植物", difficulty: "easy" },
  { word: "房子", hint: "建筑", difficulty: "easy" },
  { word: "城堡", hint: "建筑", difficulty: "easy" },
  { word: "桥", hint: "建筑", difficulty: "easy" },
  { word: "汽车", hint: "交通工具", difficulty: "easy" },
  { word: "自行车", hint: "交通工具", difficulty: "easy" },
  { word: "飞机", hint: "交通工具", difficulty: "easy" },
  { word: "船", hint: "交通工具", difficulty: "easy" },
  { word: "火车", hint: "交通工具", difficulty: "easy" },
  { word: "火箭", hint: "交通工具", difficulty: "easy" },
  { word: "蛋糕", hint: "食物", difficulty: "easy" },
  { word: "冰淇淋", hint: "食物", difficulty: "easy" },
  { word: "汉堡", hint: "食物", difficulty: "easy" },
  { word: "披萨", hint: "食物", difficulty: "easy" },
  { word: "面条", hint: "食物", difficulty: "easy" },
  { word: "鸡蛋", hint: "食物", difficulty: "easy" },
  { word: "牛奶", hint: "饮品", difficulty: "easy" },
  { word: "咖啡", hint: "饮品", difficulty: "easy" },
  { word: "书", hint: "物品", difficulty: "easy" },
  { word: "笔", hint: "物品", difficulty: "easy" },
  { word: "钥匙", hint: "物品", difficulty: "easy" },
  { word: "伞", hint: "物品", difficulty: "easy" },
  { word: "钟表", hint: "物品", difficulty: "easy" },
  { word: "眼镜", hint: "物品", difficulty: "easy" },
  { word: "手机", hint: "电子产品", difficulty: "easy" },
  { word: "电脑", hint: "电子产品", difficulty: "easy" },
  { word: "电视", hint: "电子产品", difficulty: "easy" },
  { word: "相机", hint: "电子产品", difficulty: "easy" },
  { word: "台灯", hint: "家具", difficulty: "easy" },
  { word: "椅子", hint: "家具", difficulty: "easy" },
  { word: "桌子", hint: "家具", difficulty: "easy" },
  { word: "床", hint: "家具", difficulty: "easy" },
  { word: "窗户", hint: "建筑", difficulty: "easy" },
  { word: "门", hint: "建筑", difficulty: "easy" },
  { word: "楼梯", hint: "建筑", difficulty: "easy" },
  { word: "足球", hint: "运动", difficulty: "easy" },
  { word: "篮球", hint: "运动", difficulty: "easy" },
  { word: "网球", hint: "运动", difficulty: "easy" },
  { word: "游泳", hint: "运动", difficulty: "easy" },
  { word: "跳绳", hint: "运动", difficulty: "easy" },
  { word: "心", hint: "符号", difficulty: "easy" },
  { word: "笑脸", hint: "表情", difficulty: "easy" },
  { word: "国旗", hint: "物品", difficulty: "easy" },
  { word: "气球", hint: "物品", difficulty: "easy" },
  { word: "礼物", hint: "物品", difficulty: "easy" },
  { word: "灯笼", hint: "物品", difficulty: "easy" },
  { word: "信封", hint: "物品", difficulty: "easy" },
  { word: "剪刀", hint: "工具", difficulty: "easy" },
  { word: "锤子", hint: "工具", difficulty: "easy" },
  { word: "牙刷", hint: "日用品", difficulty: "easy" },
  { word: "梳子", hint: "日用品", difficulty: "easy" },
  { word: "镜子", hint: "日用品", difficulty: "easy" },
  { word: "帽子", hint: "服饰", difficulty: "easy" },
  { word: "鞋子", hint: "服饰", difficulty: "easy" },
  { word: "手套", hint: "服饰", difficulty: "easy" },
  { word: "围巾", hint: "服饰", difficulty: "easy" },
  { word: "裙子", hint: "服饰", difficulty: "easy" },
  { word: "裤子", hint: "服饰", difficulty: "easy" },
  { word: "袜子", hint: "服饰", difficulty: "easy" },
  { word: "纽扣", hint: "服饰", difficulty: "easy" },
  { word: "戒指", hint: "饰品", difficulty: "easy" },

  // 中等 — 动作、场景、概念
  { word: "跑步", hint: "动作", difficulty: "medium" },
  { word: "跳舞", hint: "动作", difficulty: "medium" },
  { word: "唱歌", hint: "动作", difficulty: "medium" },
  { word: "睡觉", hint: "动作", difficulty: "medium" },
  { word: "吃饭", hint: "动作", difficulty: "medium" },
  { word: "洗澡", hint: "动作", difficulty: "medium" },
  { word: "读书", hint: "动作", difficulty: "medium" },
  { word: "写信", hint: "动作", difficulty: "medium" },
  { word: "钓鱼", hint: "活动", difficulty: "medium" },
  { word: "露营", hint: "活动", difficulty: "medium" },
  { word: "滑雪", hint: "运动", difficulty: "medium" },
  { word: "冲浪", hint: "运动", difficulty: "medium" },
  { word: "秋千", hint: "游乐设施", difficulty: "medium" },
  { word: "滑梯", hint: "游乐设施", difficulty: "medium" },
  { word: "摩天轮", hint: "游乐设施", difficulty: "medium" },
  { word: "过山车", hint: "游乐设施", difficulty: "medium" },
  { word: "圣诞树", hint: "节日", difficulty: "medium" },
  { word: "生日蛋糕", hint: "庆祝", difficulty: "medium" },
  { word: "蜡烛", hint: "物品", difficulty: "medium" },
  { word: "风筝", hint: "玩具", difficulty: "medium" },
  { word: "拼图", hint: "玩具", difficulty: "medium" },
  { word: "积木", hint: "玩具", difficulty: "medium" },
  { word: "雪人", hint: "冬季", difficulty: "medium" },
  { word: "沙滩", hint: "场景", difficulty: "medium" },
  { word: "火山", hint: "自然", difficulty: "medium" },
  { word: "瀑布", hint: "自然", difficulty: "medium" },
  { word: "沙漠", hint: "自然", difficulty: "medium" },
  { word: "岛屿", hint: "自然", difficulty: "medium" },
  { word: "森林", hint: "自然", difficulty: "medium" },
  { word: "海洋", hint: "自然", difficulty: "medium" },
  { word: "闪电", hint: "天气", difficulty: "medium" },
  { word: "雪花", hint: "天气", difficulty: "medium" },
  { word: "台风", hint: "天气", difficulty: "medium" },
  { word: "日出", hint: "自然现象", difficulty: "medium" },
  { word: "日落", hint: "自然现象", difficulty: "medium" },
  { word: "指南针", hint: "工具", difficulty: "medium" },
  { word: "望远镜", hint: "工具", difficulty: "medium" },
  { word: "显微镜", hint: "科学", difficulty: "medium" },
  { word: "温度计", hint: "工具", difficulty: "medium" },
  { word: "秤", hint: "工具", difficulty: "medium" },
  { word: "机器人", hint: "科技", difficulty: "medium" },
  { word: "火箭船", hint: "科幻", difficulty: "medium" },
  { word: "金字塔", hint: "建筑", difficulty: "medium" },
  { word: "风车", hint: "建筑", difficulty: "medium" },
  { word: "灯塔", hint: "建筑", difficulty: "medium" },
  { word: "教堂", hint: "建筑", difficulty: "medium" },
  { word: "帐篷", hint: "建筑", difficulty: "medium" },
  { word: "吊桥", hint: "建筑", difficulty: "medium" },
  { word: "热气球", hint: "交通工具", difficulty: "medium" },
  { word: "潜水艇", hint: "交通工具", difficulty: "medium" },
  { word: "直升机", hint: "交通工具", difficulty: "medium" },
  { word: "救护车", hint: "交通工具", difficulty: "medium" },
  { word: "消防车", hint: "交通工具", difficulty: "medium" },
  { word: "钢琴", hint: "乐器", difficulty: "medium" },
  { word: "吉他", hint: "乐器", difficulty: "medium" },
  { word: "小提琴", hint: "乐器", difficulty: "medium" },
  { word: "鼓", hint: "乐器", difficulty: "medium" },
  { word: "喇叭", hint: "乐器", difficulty: "medium" },
  { word: "麦克风", hint: "设备", difficulty: "medium" },
  { word: "耳机", hint: "设备", difficulty: "medium" },
  { word: "鼠标", hint: "电脑外设", difficulty: "medium" },
  { word: "键盘", hint: "电脑外设", difficulty: "medium" },
  { word: "打印机", hint: "设备", difficulty: "medium" },
  { word: "地铁", hint: "交通", difficulty: "medium" },
  { word: "红绿灯", hint: "交通", difficulty: "medium" },
  { word: "斑马线", hint: "交通", difficulty: "medium" },
  { word: "邮筒", hint: "公共设施", difficulty: "medium" },
  { word: "电话亭", hint: "公共设施", difficulty: "medium" },
  { word: "跷跷板", hint: "游乐设施", difficulty: "medium" },

  // 困难 — 成语、抽象概念、组合词
  { word: "画蛇添足", hint: "成语", difficulty: "hard" },
  { word: "守株待兔", hint: "成语", difficulty: "hard" },
  { word: "掩耳盗铃", hint: "成语", difficulty: "hard" },
  { word: "刻舟求剑", hint: "成语", difficulty: "hard" },
  { word: "井底之蛙", hint: "成语", difficulty: "hard" },
  { word: "对牛弹琴", hint: "成语", difficulty: "hard" },
  { word: "狐假虎威", hint: "成语", difficulty: "hard" },
  { word: "亡羊补牢", hint: "成语", difficulty: "hard" },
  { word: "杯弓蛇影", hint: "成语", difficulty: "hard" },
  { word: "鹤立鸡群", hint: "成语", difficulty: "hard" },
  { word: "外星人", hint: "科幻", difficulty: "hard" },
  { word: "美人鱼", hint: "神话", difficulty: "hard" },
  { word: "独角兽", hint: "神话", difficulty: "hard" },
  { word: "龙", hint: "神话", difficulty: "hard" },
  { word: "凤凰", hint: "神话", difficulty: "hard" },
  { word: "天使", hint: "神话宗教", difficulty: "hard" },
  { word: "恶魔", hint: "神话宗教", difficulty: "hard" },
  { word: "木乃伊", hint: "神话", difficulty: "hard" },
  { word: "吸血鬼", hint: "神话", difficulty: "hard" },
  { word: "海盗", hint: "角色", difficulty: "hard" },
  { word: "忍者", hint: "角色", difficulty: "hard" },
  { word: "骑士", hint: "角色", difficulty: "hard" },
  { word: "宇航员", hint: "职业", difficulty: "hard" },
  { word: "消防员", hint: "职业", difficulty: "hard" },
  { word: "医生", hint: "职业", difficulty: "hard" },
  { word: "厨师", hint: "职业", difficulty: "hard" },
  { word: "魔术师", hint: "职业", difficulty: "hard" },
  { word: "水族馆", hint: "场所", difficulty: "hard" },
  { word: "游乐园", hint: "场所", difficulty: "hard" },
  { word: "天文台", hint: "场所", difficulty: "hard" },
  { word: "图书馆", hint: "场所", difficulty: "hard" },
  { word: "旋转木马", hint: "游乐设施", difficulty: "hard" },
  { word: "自由女神像", hint: "地标", difficulty: "hard" },
  { word: "埃菲尔铁塔", hint: "地标", difficulty: "hard" },
  { word: "万里长城", hint: "地标", difficulty: "hard" },
  { word: "比萨斜塔", hint: "地标", difficulty: "hard" },
  { word: "金字塔", hint: "地标", difficulty: "hard" },
  { word: "表情包", hint: "网络文化", difficulty: "hard" },
  { word: "自拍杆", hint: "科技", difficulty: "hard" },
  { word: "无人机", hint: "科技", difficulty: "hard" },
  { word: "二维码", hint: "科技", difficulty: "hard" },
  { word: "充电宝", hint: "科技", difficulty: "hard" },
  { word: "不倒翁", hint: "玩具", difficulty: "hard" },
  { word: "万花筒", hint: "玩具", difficulty: "hard" },
  { word: "溜溜球", hint: "玩具", difficulty: "hard" },
  { word: "指挥家", hint: "职业", difficulty: "hard" },
  { word: "潜水员", hint: "职业", difficulty: "hard" },
  { word: "考古学家", hint: "职业", difficulty: "hard" },
  { word: "摄影师", hint: "职业", difficulty: "hard" },
  { word: "理发师", hint: "职业", difficulty: "hard" },
  { word: "拳击", hint: "运动", difficulty: "hard" },
  { word: "击剑", hint: "运动", difficulty: "hard" },
  { word: "射箭", hint: "运动", difficulty: "hard" },
  { word: "举重", hint: "运动", difficulty: "hard" },
  { word: "花样滑冰", hint: "运动", difficulty: "hard" },
  { word: "跳伞", hint: "运动", difficulty: "hard" },
  { word: "攀岩", hint: "运动", difficulty: "hard" },
  { word: "冰壶", hint: "运动", difficulty: "hard" },
  { word: "橄榄球", hint: "运动", difficulty: "hard" },
  { word: "高尔夫", hint: "运动", difficulty: "hard" },
  { word: "保龄球", hint: "运动", difficulty: "hard" },
  { word: "乒乓球", hint: "运动", difficulty: "hard" },
  { word: "台球", hint: "运动", difficulty: "hard" },
  { word: "帆船", hint: "运动", difficulty: "hard" },
  { word: "雪橇", hint: "运动", difficulty: "hard" },
  { word: "跷跷板", hint: "游乐设施", difficulty: "hard" },
  { word: "磁悬浮", hint: "科技", difficulty: "hard" },
  { word: "太阳能", hint: "能源", difficulty: "hard" },
  { word: "风能", hint: "能源", difficulty: "hard" },
  { word: "DNA", hint: "科学", difficulty: "hard" },
  { word: "地球仪", hint: "教学", difficulty: "hard" },
  { word: "沙漏", hint: "计时器", difficulty: "hard" },
  { word: "日晷", hint: "计时器", difficulty: "hard" },
  { word: "八音盒", hint: "音乐盒", difficulty: "hard" },
  { word: "投影仪", hint: "设备", difficulty: "hard" },
  { word: "复印机", hint: "设备", difficulty: "hard" },
  { word: "收银机", hint: "设备", difficulty: "hard" },
  { word: "自动售货机", hint: "设备", difficulty: "hard" },
  { word: "验钞机", hint: "设备", difficulty: "hard" },
  { word: "过山车", hint: "游乐设施", difficulty: "hard" },
  { word: "海盗船", hint: "游乐设施", difficulty: "hard" },
  { word: "跳楼机", hint: "游乐设施", difficulty: "hard" },
  { word: "大摆锤", hint: "游乐设施", difficulty: "hard" },
  { word: "碰碰车", hint: "游乐设施", difficulty: "hard" },
  { word: "摩天轮", hint: "游乐设施", difficulty: "hard" },
];

export function getRandomWords(
  count: number,
  difficulty?: "easy" | "medium" | "hard"
): GameWord[] {
  let pool = words;
  if (difficulty) {
    pool = words.filter((w) => w.difficulty === difficulty);
  }
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getRandomWord(difficulty?: "easy" | "medium" | "hard"): GameWord {
  const pool = difficulty
    ? words.filter((w) => w.difficulty === difficulty)
    : words;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getWordsForGame(
  roundCount: number,
  difficulties: ("easy" | "medium" | "hard")[] = ["easy", "medium", "hard"]
): GameWord[] {
  const perDifficulty = Math.ceil(roundCount / difficulties.length);
  const selected: GameWord[] = [];
  for (const diff of difficulties) {
    const pool = words.filter((w) => w.difficulty === diff);
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    selected.push(...shuffled.slice(0, perDifficulty));
  }
  return selected.sort(() => Math.random() - 0.5).slice(0, roundCount);
}
