import {
  type ComponentType,
  type SVGProps,
} from "react";
import {
  Toolbox,
  House,
  Wrench,
  Monitor,
  Music,
  CheckSquare,
  Puzzle,
  Share,
  MessageCircle,
  FlaskConical,
  Camera,
  Piano,
  Paintbrush,
  Files,
  FileUp,
  Video,
  Scan,
  Download,
  Swords,
  FileText,
  Lock,
  Star,
  Upload,
  FolderOpen,
  Clapperboard,
  Disc3,
  Palette,
  ListChecks,
  Timer,
  QrCode,
  ArrowLeftRight,
  Sparkles,
  CloudSun,
  Menu,
  Gauge,
  Folder,
  Users,
  Scissors,
} from "lucide-react";

type IconProps = SVGProps<SVGSVGElement>;
type IconComponent = ComponentType<IconProps>;

export const iconMap: Record<string, IconComponent> = {
  // PascalCase (used by tools.ts)
  Toolbox,
  House,
  Wrench,
  Monitor,
  Music,
  CheckSquare,
  Puzzle,
  Share,
  MessageCircle,
  FlaskConical,
  Camera,
  Piano,
  Paintbrush,
  Files,
  FileUp,
  Video,
  Scan,
  Download,
  Swords,
  FileText,
  Lock,
  Star,
  Upload,
  FolderOpen,
  Clapperboard,
  Disc3,
  Palette,
  ListChecks,
  Timer,
  QrCode,
  ArrowLeftRight,
  Sparkles,
  CloudSun,
  Menu,
  Gauge,
  Folder,
  Users,
  Scissors,
  // kebab-case aliases
  "toolbox": Toolbox,
  "house": House,
  "wrench": Wrench,
  "monitor": Monitor,
  "music": Music,
  "check-square": CheckSquare,
  "sudoku": Puzzle,
  "share": Share,
  "message-circle": MessageCircle,
  "flask-conical": FlaskConical,
  "camera": Camera,
  "piano": Piano,
  "paintbrush": Paintbrush,
  "files": Files,
  "file-up": FileUp,
  "video": Video,
  "scan": Scan,
  "download": Download,
  "swords": Swords,
  "file-text": FileText,
  "lock": Lock,
  "star": Star,
  "upload": Upload,
  "folder-open": FolderOpen,
  "clapperboard": Clapperboard,
  "disc-3": Disc3,
  "palette": Palette,
  "list-checks": ListChecks,
  "timer": Timer,
  "qr-code": QrCode,
  "arrow-left-right": ArrowLeftRight,
  "sparkles": Sparkles,
  "cloud-sun": CloudSun,
  "menu": Menu,
  "gauge": Gauge,
  "folder": Folder,
  "users": Users,
  "scissors": Scissors,
};

/* ——— Category map ——— */
import {
  FolderCog,
  Film,
  Lightbulb,
  Cpu,
} from "lucide-react";

export const categoryMap: Record<string, IconComponent> = {
  file: FolderCog,
  media: Film,
  creative: Lightbulb,
  system: Cpu,
  // aliases
  "文件": FolderCog,
  "媒体": Film,
  "创意": Lightbulb,
  "系统": Cpu,
};

export const categoryLabels: Record<string, string> = {
  file: "文件工具",
  media: "媒体工具",
  creative: "创意工具",
  system: "系统工具",
};

export type CategoryKey = "file" | "media" | "creative" | "system";